### ISSUE TITLE
Publish on npm and extract polyfill?

### ISSUE THREAD

**Issue by davidhund** [cferdinandi/getClosest#1]
Hi Chris,

Thanks for this util and your Vanilla info in general.

I love little util functions like this and often use npm. I did, however, notice you do not publish these to npm. Any particular reason to not publish your util functions there? ([getClosest() alternatives on npm](https://www.npmjs.com/search?q=closest+element)).

One other issue I have is that these util functions often share dependancies: e.g. `getClosest` might require support for `matches`, but say `getParents` might too. For this reason (and others) it might be good to extract the polyfills?

**Comment by cferdinandi** [comment]
Hey David! Not bad suggestions, but here's why I won't be implementing them:

1. I manage literally dozens of open source projects. Pushing updates to NPM is an extra thing to manage that I have no desire to support. Plus, you can install via NPM (or a `package.json` file) directly from GitHub *and* even pull specific versions. NPM is, in that way, redundant.
2. Pulling dependencies out isn't a bad idea, and at one point I had actually done so on all of my scripts... BUT, I've found that for beginners its helpful to just include everything in one file. That's my target audience, so...

Hope that all makes sense.
